In [17]:
import pandas as pd
import numpy as np

df_raw = pd.read_csv("../data/raw/raw_exoplanet_data.csv")
df_raw.shape

(2000, 8)

In [18]:
columns_needed = [
    'pl_name',
    'hostname',
    'pl_rade',
    'pl_orbsmax',
    'st_teff',
    'st_lum'
]

df = df_raw[columns_needed].copy()
df.shape

(2000, 6)

In [19]:
df_baseline = df.dropna(subset=[
    'pl_rade',
    'pl_orbsmax',
    'st_lum'
]).copy()

df_baseline.shape

(1859, 6)

In [20]:
df_baseline.isna().sum()

pl_name       0
hostname      0
pl_rade       0
pl_orbsmax    0
st_teff       1
st_lum        0
dtype: int64

In [21]:
df_physics = df_baseline.copy()

df_physics['teq_recalc'] = (
    278 *
    (df_physics['st_lum'] ** 0.25) /
    (df_physics['pl_orbsmax'] ** 0.5)
)

In [22]:
print("Baseline shape:", df_baseline.shape)
print("Physics shape:", df_physics.shape)

print("Missing teq_recalc in physics:", df_physics['teq_recalc'].isna().sum())

Baseline shape: (1859, 6)
Physics shape: (1859, 7)
Missing teq_recalc in physics: 986

In [23]:
df_physics[['st_lum', 'pl_orbsmax']].isna().sum()

(df_physics['pl_orbsmax'] <= 0).sum()
(df_physics['st_lum'] <= 0).sum()

np.int64(987)

In [24]:
df_physics[['st_lum', 'pl_orbsmax']].describe()

            st_lum   pl_orbsmax
count  1859.000000  1859.000000
mean     -0.123018     5.324457
std       0.739408    67.435425
min      -3.257270     0.006000
25%      -0.434595     0.048000
50%      -0.051380     0.087000
75%       0.325160     0.201000
max       3.800000  2000.000000

In [25]:
df_physics['st_lum_linear'] = 10 ** df_physics['st_lum']

In [26]:
df_physics['teq_recalc'] = (
    278 * 
    (df_physics['st_lum_linear'] ** 0.25) /
    (df_physics['pl_orbsmax'] ** 0.5)
)

In [27]:
df_physics['teq_recalc'].isna().sum()

np.int64(0)

In [28]:
df_physics['teq_recalc'].describe()

count    1859.000000
mean      912.185928
std       558.244011
min         2.472050
25%       521.376434
50%       830.701309
75%      1221.818440
max      7851.798950
Name: teq_recalc, dtype: float64

In [29]:
df_physics.shape

(1859, 8)

In [30]:
df_physics.nsmallest(5, 'teq_recalc')[['st_lum_linear','pl_orbsmax','teq_recalc']]

      st_lum_linear  pl_orbsmax  teq_recalc
213        0.025010      2000.0    2.472050
277        0.011220       670.0    3.495485
179        0.050386      1100.0    3.971238
1837       0.021779       518.0    4.692345
971        0.005888       156.0    6.165702

In [33]:
df_physics.shape

(1859, 8)

In [32]:
df_physics['teq_recalc'].describe()

count    1859.000000
mean      912.185928
std       558.244011
min         2.472050
25%       521.376434
50%       830.701309
75%      1221.818440
max      7851.798950
Name: teq_recalc, dtype: float64

In [34]:
df_physics['teq_recalc'].isna().sum()

np.int64(0)

In [40]:
import os
os.getcwd()

'c:\\Users\\Samyukthaa\\exoplanet-habitability-project\\notebooks'

In [42]:
df_physics.to_csv("../data/processed/physics_dataset_v2.csv", index=False)